########################################################################
# Copyright (c) Date: Tue Aug 26 16:38:42 CDT 2008 QUALCOMM INCORPORATED 
# All Rights Reserved 
# Modified by QUALCOMM INCORPORATED on Tue Aug 26 16:38:42 CDT 2008 
########################################################################


PROGRAM = test_fft32x16
QDSPARCH = -mv5
EXEC = $(PROGRAM)

ASM_SRC_DIR = ../asm_src
SRC_DIR = ../src
INCLUDES = -I../../../include -I../include

include ../../../makefile

#---------------------------------------------------------#
#  Usage "make SRC=C" if use C-based code                 #
#---------------------------------------------------------#

ifeq ($(SRC),C)
  VPATH = $(SRC_DIR)
  _C_SRCS = $(PROGRAM).c \
            fft32x16.c \
            fft_util.c
  _ASM_SRCS =  
else
  ifeq ($(QDSPARCH),-mv2)
    $(error ERROR: Attempting to build v3 code for a v2 architecture)
  endif
  VPATH = $(ASM_SRC_DIR)
  _C_SRCS = $(PROGRAM).c
  _ASM_SRCS = fft32x16.S
endif

OBJS   = $(_C_SRCS:%.c=%.o) $(_ASM_SRCS:%.S=%.o)

CC = hexagon-clang
CCF = -O3
CFLAGS = -Wall $(CCF) $(QDSPARCH) $(INCLUDES) 
ASFLAGS = -Wall $(CCF) $(QDSPARCH) $(INCLUDES) 

LD = $(CC) $(CCF)
LDFLAGS = $(QDSPARCH)
LLIBS = -lhexagon

RUN = hexagon-sim

RM = rm -rf


$(PROGRAM): $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $^ $(LLIBS) 


clean: 
	$(RM) *.o $(PROGRAM) pmu_statsfile.txt stats.txt


sim: $(PROGRAM)
	$(RUN) -- $(EXEC) 

