########################################################################
# Copyright (c) Date: Tue Aug 26 16:38:42 CDT 2008 QUALCOMM INCORPORATED 
# All Rights Reserved 
# Modified by QUALCOMM INCORPORATED on Tue Aug 26 16:38:42 CDT 2008 
########################################################################


AS=hexagon-as
ASFLAGS=-mv5 -mfalign-info
CC=hexagon-clang
CFLAGS=-mv5
LD=hexagon-ld

.PHONY: all clean

all: falign.o falign_limitations.o

clean:
	${RM} *.o
